### PR TITLE
Eric

### PR DESCRIPTION
**Pull request by EricInman**
- changed MainTabNavigator to be able to pass state along to StatTracker and Profile

- added a getUser call to ProfileView to try and get it to display user data

- added a line in LoginView and RegisterView to pass the username to MainTabNavigator

### CODE REVIEW

**Comment by ncpalmie** [comment]
Looks good to me. Once the style errors are fixed we'll be good to merge it in.

**Comment by rmfay1** [comment]
I agreed with Nathan. Once the eslint errors are good let’s push it

**Comment by Bart-Ilg** [comment]
^ agreed, its looking good bar the eslint errors

**Comment by oshorab** [comment]
Good additions to merge with master, nice. As mentioned before, once the linting errors are fixed go for it.

**Comment by mattcuento** [comment]
Nice job on the props, before closing make sure we're careful about the merge conflicts we have here, don't wanna lose anything important

**Pull request merged**
