### PR TITLE
Removing back end from front end, front end here only now

### PR DESCRIPTION
**Pull request by mattcuento**
Reformatted the project to bring deeper folders out to top level.
Removed all files to do with back end, all back end files are in the separate repository and hosted on Heroku
This repo will run the front end.

### CODE REVIEW

**Comment by rmfay1** [comment]
The redistribution of the front and back end looks good to me. Once CI is all set up it will be a beauty.

**Comment by ncpalmie** [comment]
Looks good to me, once it's merged in we can start using non-web builds for testing.

**Comment by Bart-Ilg** [comment]
reopening

**Comment by Bart-Ilg** [comment]
looks good to me, I think we should merge it

**Comment by EricInman** [comment]
Everything looks good. Should be nice having frontend and backend in separate places.

**Comment by oshorab** [comment]
Looks good to me. Separating the back end and running it on heroku fixes my issue of not being able to run on web through the metro bundler, so this seems like a good move.

**Pull request merged**
