### PR TITLE
added search bar to listview

### PR DESCRIPTION
**Pull request by rmfay1**
added search bar to listview

### CODE REVIEW

**Comment by mattcuento** [comment]
Hey Ryan, I fixed a conflict between you and barts package locks. Other than that search bar is looking great! Could you just run eslint to fix those last annotations?

**Comment by EricInman** [comment]
I think the search bar looks pretty good! Once the eslint stuff is fixed up, it should be good to go.

**Comment by oshorab** [comment]
Looks good to me, looks like the linting errors have been fixed

**Comment by Bart-Ilg** [comment]
Linting errors are fixed, good work

**Pull request closed without merging**
