### PR TITLE
Changes to navigation

### PR DESCRIPTION
**Pull request by ncpalmie**
Refactored navigation, restyled the hike details screen, added passing of parameters through navigation to allow hike details to update with selected hike information.

### CODE REVIEW

**Review by rmfay1 — APPROVED** [review]
It looks good to me!

**Comment by oshorab** [comment]
Changes look good to merge to me as well.

**Comment by mattcuento** [comment]
LGTM, everything passing!

**Review by mattcuento — APPROVED** [review]

**Comment by EricInman** [comment]
Looks good to merge!

**Comment by Bart-Ilg** [comment]
Seems good to merge!

**Comment by ncpalmie** [comment]
Thanks for the review guys, merging in now.

**Pull request merged**
